### PR TITLE
adding what other values I could find the codebase referenced

### PR DESCRIPTION
**Pull request by michaeljhopkins**

### CODE REVIEW

**Comment by AndersSchmidtHansen** [comment]
Ahhh! Now I get it. I thought you were talking about the default, blank `.env` file. I can definitely supply an .env with ALL the values used throughout the project. :)

**Comment by AndersSchmidtHansen** [comment]
@michaeljhopkins Try checking out the updated .env.example file now. :) I am considering moving most of this stuff into the database / MySQL itself though, instead of relying too much on the .env. That would make setting Sidequest up faster / easier, but I don't know yet.

**Comment by michaeljhopkins** [comment]
Personally I would lean towards a file instead of a db for two reasons. 1.) I think that will be prone to a significant increase in needless hits on the db. 2.) To manage prod vs test api keys there will still have to be a dynamic seed file (or something similar).

Big env files aren't too big of a hassle given an accurate template is kept up to date. I don't think its a surprise or unexpected to anybody that a big project with lots of moving parts will rely on several environment variables.

**Comment by AndersSchmidtHansen** [comment]
That's some good points Michael. I might be a little too obsessed with ease-of-installation. Laravel Forge is already prepared for working easily with .env files too, so let's just stick with this setup for now where '.env' is used for secret keys and the DB for public / non-critical stuff.

**Pull request closed without merging**
